import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col max-w-4xl mx-auto  min-h-screen bg-neutral-950 text-gray-100 p-8 font-mono`}
      >
        {children}

        <footer className="mt-auto flex h-12 w-full items-center justify-between border-t border-t-neutral-800">
          <p className="text-sm text-gray-400">undefined</p>
          <p className="text-sm text-gray-400">new Date().getFullYear()</p>
        </footer>
      </body>
    </html>
  );
}
